# Generated by Django 5.1.7 on 2025-03-29 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_doctorprofile_doctorschedule_patientprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorschedule',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
