# Generated by Django 5.1.7 on 2025-03-29 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_doctorschedule_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorschedule',
            name='day',
            field=models.CharField(choices=[('monday', 'Lunes'), ('tuesday', 'Martes'), ('wednesday', 'Miercoles'), ('thursday', 'Jueves'), ('friday', 'Viernes')], max_length=10),
        ),
    ]
